### ISSUE TITLE
Access to MetadataServer fake for go unit tests

### ISSUE THREAD

**Issue by VictorDebray** [salrashid123/gce_metadata_server#31]
As the currently stands, one can not use the MetadataServer for unit tests.

However, project can not import from main package. Also, it would be great to run the fake server from inside go test code, be able control what port the server binds on without having to run a compiled binary.

Is this something the repository maintainers could do ?

**Comment by salrashid123** [comment]
i do run a couple of handler tests here:

*  https://github.com/salrashid123/gce_metadata_server/blob/master/server_test.go#L67

but thats designed or the app itself; you're asking for fake to run in your app directly (eg as an import you can launch in the tests, right?). 

 For a standalone thing, i gotta think a bit more about this (if you have suggestion, LMK)

**Comment by salrashid123** [comment]
alternatively, export the variables and make the actual metadata server start from a config 

eg 

```golang
  m := mds.NewMetadataServer(h) 
  m.Start()
  defer m.Stop()
```

the above would mean refactoring the server to have  a proper way to start from `cmd/`

---

the config on test would be something like

```golang
module github.com/salrashid123/gce_metadata_server

type ServerConfig struct {
	Interface    string
	Port         string
	DomainSocket string

	UseImpersonate bool
	UseFederate    bool

	useTPM              bool
        TPMPersistentHandle int
}

type MetadataServer struct {
	tokenMutex sync.Mutex
	Creds      *google.Credentials
	Claims     Claims
	Config     ServerConfig
}
```

```golang
func TestProjectIDHandler(t *testing.T) {
	expectedProjectID := "some-project-id"

  p := getRandomPort()
  h := &mds.MetadataServer{
		Claims:  mds.Claims{
			ComputeMetadata:  mds.ComputeMetadata{
				V1: v1{
					Project: mds.Project{
						ProjectID: expectedProjectID,
					},
				},
			},
		},
    Creds:  google.FindDefaultCredentials(ctx,scopes...),
    Config: mds.ServerCOnfig{
      Interface: "127.0.0.1",
      Port: p,      
    },
	}
  m := mds.NewMetadataServer(h)
  m.Start()

  // you will need to somehow apply env-var or something:
  // GCE_METADATA_HOST=fmt.Sprintf("127.0.0.1:%s",p)
  
  //do some tests here

  defer m.Stop()
 
}
```


you're more looking for this approach, yea?

**Comment by salrashid123** [comment]
@VictorDebray i'm going to create a branch monday with these changes for you to look at.   

in tests, its like this

```golang
func TestAccessTokenCredentialHandler(t *testing.T) {
	expectedToken := "foo"
	expireInSeconds := 60

	creds := &google.Credentials{
		ProjectID: "bar",
		TokenSource: oauth2.StaticTokenSource(&oauth2.Token{
			AccessToken: expectedToken,
			Expiry:      time.Now().Add(time.Second * time.Duration(expireInSeconds)),
			TokenType:   "Bearer",
		})}

	p, err := getFreePort()

	sc := &ServerConfig{
		Port: fmt.Sprintf(":%d", p),
	}

	h, err := NewMetadataServer(context.Background(), sc, creds, &Claims{})

	err = h.Start()

	defer h.Shutdown()

	t.Setenv("GCE_METADATA_HOST", fmt.Sprintf("127.0.0.1:%d", p))

	ts, err := google.DefaultTokenSource(context.Background(), cloudPlatformScope)
	//ts := google.ComputeTokenSource("default", cloudPlatformScope)

	tok, err := ts.Token()

	if tok.AccessToken != expectedToken {
		t.Errorf("handler returned unexpected body: got %v want %v", tok.AccessToken, expectedToken)
	}
}

func TestOnGCEHandler(t *testing.T) {

	p, err := getFreePort()
	if err != nil {
		t.Errorf("error getting emulator port %v", err)
	}
	sc := &ServerConfig{
		Port: fmt.Sprintf(":%d", p),
	}

	h, err := NewMetadataServer(context.Background(), sc, &google.Credentials{}, &Claims{})

	err = h.Start()

	defer h.Shutdown()

	t.Setenv("GCE_METADATA_HOST", fmt.Sprintf("127.0.0.1:%d", p))

	if !metadata.OnGCE() {
		t.Errorf("handler returned unexpected response expected got true")
	}
}
```


---

outside of tests, you can also import and run it like this

```golang
import (
  	mds "github.com/salrashid123/gce_metadata_server"
)
	f := &mds.MetadataServer{
		Claims: &mds.Claims{},
		Creds:  google.FindDefaultCredentials(ctx, scopes...),
		ServerConfig: mds.ServerConfig{
			BindInterface:    *bindInterface,
			Port:             *port,
		},
	}

	err = f.Start()
  // do other stuff here
  defer f.Shutdown()
```


i'll use the above to setup the default launcher under `cmd/main.go` which will configure the same current cli parameters and launch the server

**Comment by VictorDebray** [comment]
Sorry I am only commenting now. Was out sick.
Yes that sounds like how I was thinking about things working!
Will  review your branch when you got it up

**Comment by VictorDebray** [comment]
For the GCE_METADATA_HOST var, I'm imagining you could give that as a string parameter to the NewMetadataServer that will return everything built in a nice way for you.

I think how you get the GCE_METADATA_HOST is an implem detail. As far as the MetadataServer is concerned, it only needs it. I would leave the cmd/main.go fetch it from env and pass it along to the constructor of MetadataServer

**Comment by salrashid123** [comment]
thanks, the candidate branch is here:   https://github.com/salrashid123/gce_metadata_server/tree/mds-fake

the `GCE_METADATA_HOST` is set in the tests incase you run something that uses a GCP  client library.  The env var isn't used inside the metadata server itself but the client library that calls it from the outside eg [this](https://github.com/salrashid123/gce_metadata_server?tab=readme-ov-file#using-google-auth-clients).   

in the tests cited above, its:

```golang
t.Setenv("GCE_METADATA_HOST", fmt.Sprintf("127.0.0.1:%d", p))
ts, err := google.DefaultTokenSource(context.Background(), cloudPlatformScope)
```

---

the server config for the test cases on the other hand tells the mds server the bind info (which for tests must match)

```golang
		ServerConfig: mds.ServerConfig{
			BindInterface:    *bindInterface,
			Port:             *port,
		},
```

**Comment by salrashid123** [comment]
added in some more changes to the docs, test cases and fixed the way `cmd/main.go` was calling the server itself.

if the changes look good, i'll merge with main 

@MikeMoore63 , i added in a some comments [here](https://github.com/salrashid123/gce_metadata_server/tree/mds-fake?tab=readme-ov-file#running-gcp-ops-agent)  about the ops agent too per your pull request the other week.   i coudn't get it to work completely with the env-var in systemd so i left it with link-local

**Comment by VictorDebray** [comment]
Changes look good! Thanks a lot. I seem to be able to import the fake well now. But have started using it in my tests yet.

**Comment by salrashid123** [comment]
commited in `3.4.0`:

https://github.com/salrashid123/gce_metadata_server/releases/tag/3.4.0

thanks!

**Comment by MikeMoore63** [comment]
> added in some more changes to the docs, test cases and fixed the way `cmd/main.go` was calling the server itself.
> 
> if the changes look good, i'll merge with main
> 
> @MikeMoore63 , i added in a some comments [here](https://github.com/salrashid123/gce_metadata_server/tree/mds-fake?tab=readme-ov-file#running-gcp-ops-agent) about the ops agent too per your pull request the other week. i coudn't get it to work completely with the env-var in systemd so i left it with link-local

I raised this issue https://github.com/GoogleCloudPlatform/ops-agent/issues/1630 its the local healthe check has this hard coded they say its none blocking and should still work. Was it healthcheck failure as described o rmore ? I have kept alias similarly to just avoid ths error message.

**Comment by salrashid123** [comment]
@MikeMoore63 we can pick this up on the original PR you filed but to close this out, i the ops-agent services simply woudnt' startup (vs just the healthcheck failing).  

I also updated the readme here with:

"One of the main issues with running the ops-agent off GCP is that it is by default expecting to emit data for [resource.type=gce_instance](https://cloud.google.com/monitoring/api/resources#tag_gce_instance) ([here](https://github.com/GoogleCloudPlatform/ops-agent/blob/master/confgenerator/resourcedetector/detector.go#L54)]). For true support of on-prem instances, it should emit with support for [resource.type=generic_node](https://cloud.google.com/monitoring/api/resources#tag_generic_node) and [resource.type=generice_task](https://cloud.google.com/monitoring/api/resources#tag_generic_task). Those two resource types indicate arbitrary computing environments. For background on those types, see [Writing Developer logs with Google Cloud Logging](https://blog.salrashid.dev/articles/2019/writing_developer_logs/) .."
