### ISSUE TITLE
static string after refactor

### ISSUE THREAD

**Issue by oogetyboogety** [salrashid123/gce_metadata_server#4]
it's not clear how to pass a static string as the service token after the go refactor. is this something that is already implemented in the configuration of the google cloud go library's JSON file?

**Comment by salrashid123** [comment]
There isn't a way to do that currently but i can add that bit in very shortly...(i just didn't realize anyone was using that specific mode).   You'd like this added back in yea?

https://github.com/salrashid123/gce_metadata_server/blob/fd85602548ea30b2f80c98a01164853c9f160298/README.md#using-static-environment-variables

**Comment by oogetyboogety** [comment]
Yup that's it, was useful to pass that in from the kubectl secret for the service token



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by salrashid123** [comment]
ok, can you give this a try before i commit and bake it into the docker image?
 https://gist.github.com/salrashid123/26af6cabecc41c26473d2133ff37556a#file-main-go-L380

the usage is like this:

```
export GOOGLE_ACCESS_TOKEN=`gcloud auth print-access-token`
export GOOGLE_PROJECT_ID=`gcloud config get-value core/project`
export GOOGLE_NUMERIC_PROJECT_ID=`gcloud projects describe $GOOGLE_PROJECT_ID --format="value(projectNumber
export GOOGLE_ACCOUNT_EMAIL=`gcloud config get-value core/account`


go run main.go -logtostderr  -alsologtostderr -v 5  -port :8080  --tokenScopes https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform
```

if you create a docker container, 
```
docker run  \
  -v `pwd`/certs/:/certs/ \ 
  -p 8080:8080 \ 
  -t salrashid123/gcemetadataserver  \
  -logtostderr -alsologtostderr -v 5 \ 
  -e GOOGLE_ACCESS_TOKEN=some_static_token \
  -e GOOGLE_NUMERIC_PROJECT_ID=12345 \ 
  -e GOOGLE_PROJECT_ID=my_project \
  -e GOOGLE_ACCOUNT_EMAIL=metadata-sa-@$GOOGLE_PROJECT_ID.iam.gserviceaccount.com gcemetadataserver \
  -port :8080  \ 
  -tokenScopes https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/cloud-platform
```

**Comment by salrashid123** [comment]
i committed the change and updated the docker image
