### ISSUE TITLE
Idea: Support for Workload Identity Federation

### ISSUE THREAD

**Issue by EronWright** [salrashid123/gce_metadata_server#8]
I wonder if this server could be combined with the federated TokenSource providers in [salrashid123/oauth2](https://github.com/salrashid123/oauth2), to enable workloads running outside of Google Cloud to authenticate with a federated identity while using the ordinary Google Cloud libraries, as described in [Accessing Resources from AWS](https://cloud.google.com/iam/docs/access-resources-aws).

The idea would be to have the metadata server serve up the access token produced by a configured TokenSource. In concept, this would allow a pod running in EKS to use its KSA to assume an AWS IAM role (as described [here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html)), and then impersonate a GSA, without any code changes.  Does this seem reasonable?

**Comment by salrashid123** [comment]
we're working on adding in direct support for federation into gcp client libraries (i.,e you'd 'just use' GCP libraries on aws as usual but behind the scenes the federation takes place).  at the moment, its still in progress but if you're a gcp customer, pls contact your TAM or customer engineer for followups on this.

btw, which language are you primarily interested in (i assume golang)?

**Comment by EronWright** [comment]
Thanks @salrashid123 for the insight.  I'm specifically interested in using cert-manager, external-dns, and [prometheus-stackdriver](https://github.com/prometheus-community/stackdriver_exporter) in an AWS environment in combination with Cloud DNS and Cloud Monitoring.

**Comment by salrashid123** [comment]
for ref, gcp now support automatic exchange of aws using the application default  creds

 https://github.com/salrashid123/gcpcompat-aws#automatic-exchange
